### PR TITLE
Some test failed

### PR DESCRIPTION
**Pull request by BoPeng**
Checklist
* [ x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x ] Ensured the license file is being packaged.

https://anaconda.org/conda-forge/sos-notebook/files 
only linux binary was created.

### CODE REVIEW

**Comment by jdblischak** [comment]
@conda-forge-admin, please rerender

**Comment by BoPeng** [comment]
I released a new version of sos notebook and removed `noarch:python` due to https://github.com/conda-forge/staged-recipes/issues/9465 . All tests passed but only linux binary is built (see https://anaconda.org/conda-forge/sos-notebook/files). This PR bumps build number and it is obvious that the recipe is only tested for linux.

@hmaarrfk Could you help me check why the recipe became linux-only?

**Comment by jdblischak** [comment]
> only linux binary was created.

@BoPeng Only the Linux binary was built because you didn't "rerender" (this is the conda-forge term for updating the CI config files in the repo) after removing `noarch: python` in commit https://github.com/conda-forge/sos-notebook-feedstock/commit/66146cd4cb41f68175dc0a81377587cd4c873173

**Comment by jdblischak** [comment]
Or maybe not. That's strange.

**Comment by jdblischak** [comment]
> I tried to build for you, but it looks like I wasn't able to push to the vatlab branch of sos-notebook-feedstock/re-render. Did you check the "Allow edits from maintainers" box?

@BoPeng Do you have "Allow edits from maintainers" enabled?

**Comment by BoPeng** [comment]
> Do you have "Allow edits from maintainers" enabled?

I do not know how.

**Comment by jdblischak** [comment]
There should be a checkbox on the right side that you can click:

https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by hmaarrfk** [comment]
Rerendering has become problematic over the last few days.

Locally, type `conda install -n base conda-smithy`

`conda-smithy rerender`

or something like that to get the recipe to regenerate itself.

**Comment by BoPeng** [comment]
> There should be a checkbox on the right side that you can click:

It is already selected.

**Comment by jdblischak** [comment]
> It is already selected.

According to @hmaarrfk, the conda-forge-admin bot has been having trouble recently. Thus that checkbox isn't the problem.

I rerendered locally (`conda-smithy rerender --commit=auto`) and opened a new PR. This should build the binary for the other platforms: #21

**Comment by BoPeng** [comment]
@isuruf I am using `# [py<36]` now, but can you tell why only the linux tests are running?

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Pull request closed without merging**
