### PR TITLE
Rerender and reformat Python skipping

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Rerendered after switch to noarch in https://github.com/conda-forge/sos-notebook-feedstock/commit/66146cd4cb41f68175dc0a81377587cd4c873173

### CODE REVIEW

**Comment by BoPeng** [comment]
```
TEST END: D:\bld\win-64\sos-notebook-0.20.2-py37_0.tar.bz2
Renaming work directory,  D:\bld\sos-notebook_1568045115842\work  to  D:\bld\sos-notebook_1568045115842\work_moved_sos-notebook-0.20.2-py>=36_0_win-64_main_build_loop
Traceback (most recent call last):
  File "C:\Miniconda\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\bld\\sos-notebook_1568045115842\\work' -> 'D:\\bld\\sos-notebook_1568045115842\\work_moved_sos-notebook-0.20.2-py>=36_0_win-64_main_build_loop'
```
The error looks like an invalid path name, which is true because `>` is not an acceptable character. 

@conda-forge/help-python Is this a bug with conda itself? How should I fix it?

**Comment by isuruf** [comment]
See https://conda-forge.org/docs/maintainer/adding_pkgs.html?highlight=skip#skipping-builds on how to skip python builds.

**Comment by BoPeng** [comment]
@isuruf : we are not trying to skip windows build. `sos-notebook` is supposed to work under windows and the recipe worked under windows with `noarch: python`.

**Comment by isuruf** [comment]
Hmm, I'm not sure what you are talking about. Following doesn't skip windows. It skips python <3.6
```
build:
    skip: true  # [py<36]
```

**Comment by BoPeng** [comment]
Sorry, my mistake, but the failed test used python 3.7 so adding `skip: true [py<36]` would not help.

**Comment by isuruf** [comment]
You are using the wrong syntax for skipping python builds. That's the root of the issue you are seeing.

**Comment by BoPeng** [comment]
ok, so we are seeing exactly the same problem as [calysto_bash](https://ci.appveyor.com/project/conda-forge/calysto-bash-feedstock/branch/master/job/2aiwdrpaq4ylkpku) and we will have to fix it to get windows binary.

**Comment by BoPeng** [comment]
@jdblischak Could you apply the following patch
```diff
diff --git a/recipe/run_test.py b/recipe/run_test.py
index c0edc7a..d08ef5d 100644
--- a/recipe/run_test.py
+++ b/recipe/run_test.py
@@ -3,7 +3,7 @@
 import jupyter_client

 try:
-    jupyter_client.kernelspec.get_kernel_spec('sos')
+    print(jupyter_client.kernelspec.get_kernel_spec('sos').to_dict())
 except jupyter_client.kernelspec.NoSuchKernel:
     print('sos kernel was not installed')
     print('The following kernels are installed:')
```
to check what spec file that AppVeyor is seeing?

**Comment by BoPeng** [comment]
The patch does not work (format issue). It's a temporary patch for debug purposes, perhaps you can change the file directly.

**Comment by jdblischak** [comment]
> The patch does not work (format issue). It's a temporary patch for debug purposes, perhaps you can change the file directly.

I missed that the patch was for a recipe file. Patches are to update the source code from the downloaded tarball. Recipe files should just be edited directly.

**Comment by jdblischak** [comment]
Here is the relevant [output from AppVeyor](https://ci.appveyor.com/project/conda-forge/sos-notebook-feedstock/builds/27310508#L1004):

```
(%PREFIX%) %SRC_DIR%>"%PREFIX%\python.exe" -s "%SRC_DIR%\run_test.py" 
===== testing package: sos-notebook-0.20.2-py36_1 =====
running run_test.py
{'argv': ['C:\\bld\\sos-notebook_1568124002483\\_h_env\\python.exe', '-m', 'sos_notebook.kernel', '-f', '{connection_file}'], 'env': {}, 'display_name': 'SoS', 'language': 'sos', 'interrupt_mode': 'signal', 'metadata': {}}
C:\bld\sos-notebook_1568124002483\_test_env\lib\site-packages\jupyter_client\manager.py:72: DeprecationWarning: KernelManager._kernel_name_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
 def _kernel_name_changed(self, name, old, new):
E
======================================================================
ERROR: testKernel (__main__.TestSoSKernel)
----------------------------------------------------------------------
Traceback (most recent call last):
 File "C:\bld\sos-notebook_1568124002483\test_tmp\run_test.py", line 26, in testKernel
 with sos_kernel() as kc:
 File "C:\bld\sos-notebook_1568124002483\_test_env\lib\contextlib.py", line 81, in __enter__
 return next(self.gen)
 File "C:\bld\sos-notebook_1568124002483\_test_env\lib\site-packages\sos_notebook\test_utils.py", line 50, in sos_kernel
 yield start_sos_kernel()
 File "C:\bld\sos-notebook_1568124002483\_test_env\lib\site-packages\sos_notebook\test_utils.py", line 73, in start_sos_kernel
 KM, KC = test_utils.start_new_kernel(kernel_name='sos')
 File "C:\bld\sos-notebook_1568124002483\_test_env\lib\site-packages\ipykernel\tests\utils.py", line 41, in start_new_kernel
 return manager.start_new_kernel(startup_timeout=STARTUP_TIMEOUT, **kwargs)
 File "C:\bld\sos-notebook_1568124002483\_test_env\lib\site-packages\jupyter_client\manager.py", line 468, in start_new_kernel
 km.start_kernel(**kwargs)
 File "C:\bld\sos-notebook_1568124002483\_test_env\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
 **kw)
 File "C:\bld\sos-notebook_1568124002483\_test_env\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
 return launch_kernel(kernel_cmd, **kw)
 File "C:\bld\sos-notebook_1568124002483\_test_env\lib\site-packages\jupyter_client\launcher.py", line 138, in launch_kernel
 proc = Popen(cmd, **kwargs)
 File "C:\bld\sos-notebook_1568124002483\_test_env\lib\subprocess.py", line 709, in __init__
 restore_signals, start_new_session)
 File "C:\bld\sos-notebook_1568124002483\_test_env\lib\subprocess.py", line 997, in _execute_child
 startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
----------------------------------------------------------------------
Ran 1 test in 0.062s
FAILED (errors=1)
(%PREFIX%) %SRC_DIR%>IF 1 NEQ 0 exit 1 
Tests failed for sos-notebook-0.20.2-py36_1.tar.bz2 - moving package to C:\bld\broken
WARNING:conda_build.build:Tests failed for sos-notebook-0.20.2-py36_1.tar.bz2 - moving package to C:\bld\broken
WARNING conda_build.build:tests_failed(2230): Tests failed for sos-notebook-0.20.2-py36_1.tar.bz2 - moving package to C:\bld\broken
TESTS FAILED: sos-notebook-0.20.2-py36_1.tar.bz2
```

**Comment by jdblischak** [comment]
However, the [Azure Windows build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=71023&view=logs&jobId=f97ca392-d626-52d0-4b2e-4b27aa319a77&taskId=3002d0ca-d910-5264-f0e4-809a5057fac4&lineStart=707&lineEnd=708&colStart=1&colEnd=1) succeeded without any issues:

```
(%PREFIX%) %SRC_DIR%>"%PREFIX%\python.exe" -s "%SRC_DIR%\run_test.py" 
===== testing package: sos-notebook-0.20.2-py36_1 =====
running run_test.py
{'argv': ['D:/bld/sos-notebook_1568122543386/_test_env\\python.exe', '-m', 'sos_notebook.kernel', '-f', '{connection_file}'], 'env': {}, 'display_name': 'SoS', 'language': 'sos', 'interrupt_mode': 'signal', 'metadata': {}}
D:\bld\sos-notebook_1568122543386\_test_env\lib\site-packages\jupyter_client\manager.py:72: DeprecationWarning: KernelManager._kernel_name_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
  def _kernel_name_changed(self, name, old, new):
.
----------------------------------------------------------------------
Ran 1 test in 5.757s

OK

(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit 1 

(%PREFIX%) %SRC_DIR%>call "%SRC_DIR%\run_test.bat" 

(%PREFIX%) %SRC_DIR%>jupyter kernelspec list   | findstr \share\jupyter\kernels\sos 
  sos        %PREFIX%\share\jupyter\kernels\sos

(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit /B 1 

(%PREFIX%) %SRC_DIR%>jupyter run --kernel=sos ex.py 
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit /B 1 

(%PREFIX%) %SRC_DIR%>exit /B 0 

(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit 1 

Resource usage statistics from testing sos-notebook:
   Process count: 6
   CPU time: Sys=0:00:02.2, User=0:00:05.4
   Memory: 189.2M
   Disk usage: 2.0K
   Time elapsed: 0:00:18.2

TEST END: D:\bld\win-64\sos-notebook-0.20.2-py36_1.tar.bz2
```

**Comment by jdblischak** [comment]
Thus I propose that we just remove the AppVeyor build. It's not needed if the binary can be built on Azure. @BoPeng Is there any particular reason you would want to keep the AppVeyor build?

https://conda-forge.org/docs/maintainer/infrastructure.html#appveyor

**Comment by BoPeng** [comment]
> {'argv': ['C:\\bld\\sos-notebook_1568124002483\\_h_env\\python.exe', '-m', 'sos_notebook.kernel', '-f', '{connection_file}'], 'env': {}, 'display_name': 'SoS', 'language': 'sos', 'interrupt_mode': 'signal', 'metadata': {}}
C:\bld\sos-notebook_1568124002483\_test_env\lib\site-packages\jupyter_client\manager.py:72: DeprecationWarning: KernelManager._kernel_name_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
 def _kernel_name_changed(self, name, old, new):

At least we see the problem: `_h_env` for `argv` and `_test_env` for tests, so `_test_env` cannot find python under `_h_env`. This is exactly the same problem with `calysto_bash` kernel as I reported  at https://github.com/conda-forge/staged-recipes/issues/9493

**Comment by BoPeng** [comment]
> @BoPeng Is there any particular reason you would want to keep the AppVeyor build?
> https://conda-forge.org/docs/maintainer/infrastructure.html#appveyor

The documentation on this is sparse, I have no problem skipping this build as long as the windows binary can be correct generated. Right now, the spec file will not be useful even if `'D:/bld/sos-notebook_1568122543386/_test_env\\python.exe'` is used in the spec file (no `_test_env` in production environment).

Edit: I see that AppVeyor is not excluded after your patch.

**Comment by djsutherland** [comment]
@jdblischak, you accidentally had the `provider` directive indented under `appveyor` in `conda-forge.yml`, so it didn't work. Fixed that for you.

**Comment by BoPeng** [comment]
Even if we remove the appveyor tests, the python path in spec file might still be saved as `'D:/bld/sos-notebook_1568122543386/_test_env\\python.exe'` if the "official" binary build uses `_test_env`. We can merge and see, or we can apply a patch and use relative path windows.

**Comment by BoPeng** [comment]
The windows binary has just been built, with content of the spec file being

```
{
   "argv":[
      "D:\\bld\\sos-notebook_1568229271543\\_h_env\\python.exe",
      "-m",
      "sos_notebook.kernel",
      "-f",
      "{connection_file}"
   ],
   "display_name":"SoS",
   "language":"sos"
}
```
which, if copied in verbatim during installation, will unlikely work.

**Comment by BoPeng** [comment]
Confirmed to work under windows. Finally.

**Pull request merged**
