### PR TITLE
Try again...

### PR DESCRIPTION
**Pull request by BoPeng**
Checklist
* [ x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ x] Bumped the build number (if the version is unchanged)
* [ x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by BoPeng** [comment]
@conda-forge-admin, please rerender

**Comment by BoPeng** [comment]
@isuruf rerender does not seem to work . I do have "Allow edits from maintainers" selected. Note that my branch is not called `sos-notebook-feedstock/re-render`

image

**Comment by jdblischak** [comment]
@BoPeng We discussed in PR #20 that the web service is not currently working. See https://github.com/conda-forge/sos-notebook-feedstock/pull/20#issuecomment-529529389.

You'll have to rerender manually. In your terminal, run the following:

```
conda install -c conda-forge conda-smithy
conda-smithy rerender --commit=auto
git push origin build_again
```

(note that you may want to install conda-smithy in a conda environment. It installs `git` without bash completion)

**Comment by BoPeng** [comment]
```
$ conda-smithy rerender --commit=auto

Traceback (most recent call last):
  File "/Users/bpeng1/anaconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/Users/bpeng1/anaconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 485, in main
    args.subcommand_func(args)
  File "/Users/bpeng1/anaconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 353, in __call__
    check=args.check
  File "/Users/bpeng1/anaconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 1407, in main
    check_version_uptodate(r, "conda-smithy", __version__, error_on_warn)
  File "/Users/bpeng1/anaconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 1311, in check_version_uptodate
    raise RuntimeError("{} Exiting.".format(msg))
RuntimeError: conda-smithy version in root env (3.4.0) is out-of-date (3.4.5). Exiting.
```

I am seriously multi-tasking and do not have time to debug this issue. Could you handle the `[py>36]` issue in your PR?

**Comment by jdblischak** [comment]
Done in https://github.com/conda-forge/sos-notebook-feedstock/pull/21/commits/6ff837aef6b804b58549f2f349dfa0a96a97b99a

**Pull request closed without merging**
